version: "3"
services:
  proxy-server:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"

  web-server:
    restart: always
    image: nginx:latest
    volumes:
      - ./myweb:/usr/share/nginx/html

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./node:/usr/app
    restart: always
    command: ["npm", "start"]

  mysql-server:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=temporaryDB
    ports:
      - "33061:33061"
    container_name: mysql
